---
title: "Intento cálculo agrupado perímetros"
author: "Luis Daniel Chavarría"
date: "9/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# No completé trayectorias por perímetros

Porcentaje perímetros

```{r}

calcular_perimetros <- function(perimetro, documento) {
  eval(
    substitute(
(desarrollos_final %>% filter(ELTDEC_numero == perimetro & xx == "OK") %>% count() %>% as.numeric()) / 
(desarrollos_final %>% filter(ELTDEC_numero == perimetro & xx != "NO APLICA") %>% count() %>% as.numeric()),
list(xx=as.name(documento))
              )
      )
}
```

## Cálculo agrupado por perímetro

38 perímetros que necesitan trayectorias individuales

```{r}
por_perimetros_wide <- desarrollos_final %>%
  group_by(ELTDEC_numero, DIRECTION) %>%
  summarize(
    completion_mds = sum(MDS_ok == "OK") / sum(MDS_ok == "OK" |
                                                 MDS_ok == "NOT OK"),
    completion_2d = sum(`2D_ok` == "OK") / sum(`2D_ok` == "OK" |
                                                 `2D_ok` == "NOT OK"),
    completion_3d = sum(`3D_ok` == "OK") / sum(`3D_ok` == "OK" |
                                                 `3D_ok` == "NOT OK")
  )

tidy_perimetros <- por_perimetros_wide %>% 
  pivot_longer(starts_with("completion"),
               names_to = "indicador",
               values_to = "valor")
```


```{r}
calcular_perimetros("11", "3D_ok")

tibble(date = seq.Date(from = ymd("2019-10-09"), to = ymd("2020-01-30"), by = 7),
       tray_11_mds = seq(from = calcular_perimetros("11", "MDS_ok"), to = 1, length.out = 17),
       tray_11_2d = seq(from = calcular_perimetros("11", "2D_ok"), to = 1, length.out = 17),
       tray_11_3d = seq(from = calcular_perimetros("11", "3D_ok"), to = 1, length.out = 17),
       tray_12_mds = seq(from = calcular_perimetros("12", "MDS_ok"), to = 1, length.out = 17))
```

Tocaría hacerlo 114 veces, impráctico, buscar un loop?

```{r}
trays <- tibble(date = seq.Date(from = ymd("2019-10-09"), to = ymd("2020-01-30"), by = 7))

for (i in as.numeric(por_perimetros_wide$ELTDEC_numero[1:31])) {
  output <- trays %>% 
    mutate(assign(paste0("tray_",i,"_", "mds"), seq(from = calcular_perimetros(i, "MDS_ok"), to = 1, length.out = 17)))
}

calcular_perimetros("11", "MDS_ok")

for (i in as.numeric(por_perimetros_wide$ELTDEC_numero[1:31])) {
  print(i)
}

assign(paste0("tray_",11,"_", "mds"), seq(from = calcular_perimetros(11, "MDS_ok"), to = 1, length.out = 17))

trays %>% 
    mutate(assign(paste0("tray_",i,"_", "mds"), seq(from = calcular_perimetros(i, "MDS_ok"), to = 1, length.out = 17)))

```



